doc_gen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("document/", views.DocumentListView.as_view(), name="doc-view"),
    path("document/add/", views.DocumentCreateView.as_view(), name="doc-add"),
    path("document/<pk>/", views.DocumentMetaDetailView.as_view(), name="doc-detail"),
    path("document/<pk>/update/", views.DocumentUpdateView.as_view(), name="doc-update"),
    path("document/<pk>/delete/", views.DocumentDeleteView.as_view(), name="doc-delete"),
    path("document_meta/<pk>/delete/", views.DocumentMetaDeleteView.as_view(), name="doc-meta-delete"),

    path("template/", views.TemplateListView.as_view(), name="template-view"),
    path("template/add/<pk>", views.TemplateCreateView.as_view(), name="template-add"),
    path("template/add/", views.TemplateCreateView.as_view(), name="template-add"),
    path("template/<pk>", views.TemplateDetailView.as_view(), name='template-detail'),
    path("template/<pk>/update/", views.TemplateUpdateView.as_view(), name="template-update"),
    path("template/<pk>/delete/", views.TemplateDeleteView.as_view(), name="template-delete"),

    path('generate/', views.GenerateDocumentView.as_view(), name='generate'),
]

stormbreaker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls') ),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('doc_gen.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

doc_gen/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy
from django.db.models.signals import post_save
from django.dispatch import receiver
import csv
# Create your models here.
    


class DocumentMeta(models.Model):
    meta = models.CharField(unique=True, verbose_name='Meta Format', max_length=200,help_text='Enter the META format for the data', blank=True )

    def __str__(self):
        return str(self.meta)

class DocumentFile(models.Model):
    meta = models.ForeignKey( DocumentMeta,verbose_name='Meta for document', on_delete=models.CASCADE)
    data_file = models.FileField(verbose_name='Data File', help_text='Upload the file containing the datasets (.csv, .json, ...)',upload_to='data/')
    created = models.DateTimeField("created at:", auto_now=False, auto_now_add=True)

    def __str__(self):
        return f'{ str(self.data_file)} '
    def get_absolute_url(self):
        return reverse_lazy("doc-detail", kwargs={"pk": self.meta.pk})
    

class Template(models.Model):
    name = models.CharField(verbose_name = 'Template Name', max_length=50)
    doc_meta = models.ForeignKey(DocumentMeta, on_delete=models.CASCADE)
    template = RichTextField()

    
    def get_absolute_url(self):
        return reverse_lazy("template-detail", kwargs={"pk": self.pk})
    

    def __str__(self):
        return str(self.name)
    

# @receiver(post_save, sender=DocumentMeta)
# def create_meta(sender, instance, **kwargs):
#     if str(instance.data_file).split('.')[-1] == 'csv':
#         with open(instance.data_file.path, "r") as f:
#             reader = csv.reader(f)
#             i = next(reader)
#             i.sort()
#             if instance.meta != str(i):
#                 instance.meta = str(i)
#                 instance.save()                           

doc_gen/forms.py
from .models import DocumentMeta,Template,DocumentFile
from django import forms

class DocumentMetaForm(forms.ModelForm):
    
    class Meta:
        model = DocumentFile
        fields = ['data_file']

class TemplateForm(forms.ModelForm):
    next = forms.CharField(required=False,widget=forms.HiddenInput())

    class Meta:
        model = Template
        fields = '__all__'

class GenerationForm(forms.Form):
    file = forms.ModelChoiceField(DocumentFile.objects.all(),help_text = 'File')
    template = forms.ModelChoiceField(Template.objects.all(),help_text= 'Template')
    row = forms.IntegerField( required=True)

doc_gen/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView,FormView
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.http import HttpResponse
from . import models
from . import forms
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect
# Create your views here.
import csv
import json
from io import StringIO
from jinja2 import Template 

class DocumentListView(LoginRequiredMixin,ListView):
    model = models.DocumentMeta
    template_name = 'document_list.html'
    
class DocumentCreateView(LoginRequiredMixin,CreateView):
    form_class = forms.DocumentMetaForm
    template_name = "generic_form.html"

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        request.POST._mutable = True
        document = self.request.FILES['data_file']
        if str(document).split('.')[-1] == 'csv':
            csvf = StringIO(document.read().decode())
            reader = csv.reader(csvf, delimiter=',')
            i = next(reader)
            i.sort()
            form.data['meta'] = str(i)
            print(i)
        elif str(document).split('.')[-1] == 'json':
            json_data = json.loads(document.read().decode())
            # print(sorted(json_data[0].keys()))
            form.data['meta'] = str(sorted(json_data[0].keys()))

        print('form received')
        if form.is_valid():
            print('form valid ')
            instance = form.save(commit=False)
            meta_instance,created = models.DocumentMeta.objects.get_or_create(meta=form.data['meta'])
            instance.meta = meta_instance
            return self.form_valid(form,*args,**kwargs)
        else:
            return self.form_invalid(form,*args,**kwargs)


class DocumentUpdateView(LoginRequiredMixin,UpdateView):
    model = models.DocumentFile
    form_class = forms.DocumentMetaForm
    template_name = "generic_form.html"

class DocumentDeleteView(LoginRequiredMixin,DeleteView):
    model = models.DocumentFile
    template_name = "delete_confirm.html"
    success_url = reverse_lazy('doc-view')

class DocumentMetaDeleteView(LoginRequiredMixin,DeleteView):
    model = models.DocumentMeta
    template_name = "delete_confirm.html"
    success_url = reverse_lazy('doc-view')

class DocumentMetaDetailView(LoginRequiredMixin,DetailView):
    model = models.DocumentMeta
    template_name = "document_detail.html"
    context_object_name = "document"

class TemplateListView(LoginRequiredMixin,ListView):
    model = models.Template
    template_name = "template_list.html"
        
class TemplateCreateView(LoginRequiredMixin,CreateView):
    model = models.Template
    form_class = forms.TemplateForm
    template_name = "generic_form.html"

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs()
        redirect = self.request.GET.get('next')
        print(redirect)
        if redirect:
            if 'initial' in kwargs.keys():
                kwargs['initial'].update({'next': redirect})
            else:
                kwargs['initial'] = {'next': redirect}
        return kwargs


    def form_valid(self, form):
        redirect = form.cleaned_data.get('next')
        print(redirect)
        if redirect:
            self.success_url = redirect
        return super().form_valid(form)

    def get_initial(self):
        if 'pk' in self.kwargs:
            initial = super().get_initial()
            initial = initial.copy()
            initial['doc_meta'] = self.kwargs['pk']
            print(initial)
            return initial
        else:
            return super().get_initial()

class TemplateDetailView(LoginRequiredMixin,DetailView):
    model = models.Template
    context_object_name = 'template'
    template_name = 'template_detail.html'

class TemplateUpdateView(LoginRequiredMixin,UpdateView):
    model = models.Template
    form_class = forms.TemplateForm
    template_name = "generic_form.html"

class TemplateDeleteView(LoginRequiredMixin,DeleteView):
    model = models.Template
    template_name = "delete_confirm.html"
    success_url = reverse_lazy('template-detail')


class GenerateDocumentView(LoginRequiredMixin,FormView):
    form_class = forms.GenerationForm
    template_name = 'generic_form.html'
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            file = models.DocumentFile.objects.get(pk=form.data['file'])
            template = models.Template.objects.get(pk= form.data['template'])
            print(file.data_file)
            if 'csv' in str(file.data_file):
                reader = csv.DictReader(StringIO(file.data_file.read().decode()))
            else: 
                reader = json.loads(file.data_file.read())
            row = list(reader)[form.cleaned_data['row']]
            kwargs = dict(row)
            print(template.template)
            jinja_template = Template(template.template)
            bootstrap = '''
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/lux/bootstrap.min.css" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
            <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
            <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>'''
            return HttpResponse(bootstrap+jinja_template.render(**kwargs))
        else:
            return self.form_invalid(form, **kwargs)

doc_gen/templates/document_detail.html
{% extends 'base.html' %}

{% block content %}


<br>
<div class="container">
<h3 class='text-center'> Meta: {{ document.meta }} </h3>
<br>
<br>
<form class="form-group" action="{% url 'generate' %}" method='post'>
{% csrf_token %}
<div class="jumbotron">
    <h4> Data Sets </h4>
    <a class="btn btn-primary" href="{% url 'doc-add' %}">Add Dataset</a>
    <hr>

    <table class="table table-striped table-hover">
    {% for file in document.documentfile_set.all %}
        <tr>
        <td><input type="radio" name="file" value="{{file.pk}}" class="form-control"></td>    
        <td>{{file}}</td>
        <td><button type=button class="btn btn-danger" onclick="deleteClass('{% url 'doc-delete' file.pk %}'); return false;"><span class="fa fa-trash"></span></button></td> 
        </tr>
    {% endfor %}
    </table>
    <hr>
</div>
<br>

<div class="row">
    <div class="col-8">
            <label>Row Index:</label>
        <input class='form-control' name='row' value='0' type='number'>
    </div>
    <div class="col-4">
        <br>
        <button type='submit' class='btn btn-success' style='width: 100%;'>Generate</button>
    </div>
</div>

<br><br>
<div class="jumbotron">
        
    <h4> Templates </h4>
    <a class="btn btn-primary" href="{% url 'template-add' document.pk %}?next={{request.path}} ">Add Template</a>
    <hr>
    <form>
    <table class="table table-striped table-hover">
    {% for template in document.template_set.all %}
    <tr>
        <td><input type="radio" name="template" value="{{template.pk}}" class="form-control"></td>
        <td>{{template}}</td>
        <td><button  type=button class="btn btn-danger" onclick="deleteTemplate('{% url 'template-delete' template.pk %}'); return false;"><span class="fa fa-trash"></span></button></td>
    </tr>
    {% endfor %}
    </table>
    <hr>
</div>

</form>
</div>

<script>
    function deleteClass(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Document ?','body': response, 'url':url });
            }
        });
    }
    function deleteTemplate(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Template ?','body': response, 'url':url });
            }
        });
    }
</script>
{% endblock content %}

doc_gen/templates/document_list.html
{% extends 'base_list.html' %}
{% block table %}
<thead>
<th>ID</th>
<th>Meta</th>
<th>Edit</th>
<th>Delete</th>
</thead>
<tbody>
{% for document in object_list %}
<tr>
    <td>{{document.id}}</td>
    <td>{{document.meta}}</td>
    <td><a class="btn btn-primary" href="{% url 'doc-detail' document.pk %}"><span class="fa fa-pen"></span></a></td>
    <td><button class="btn btn-danger" onclick="deleteClass('{% url 'doc-meta-delete' document.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>


<script>
    function deleteClass(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Document ?','body': response, 'url':url });
            }
        });
    }
</script>
{% endblock table %}

doc_gen/templates/template_detail.html
{% extends 'base.html' %}

{% block content %}


<br>
<div class="container">
<h1 class='text-center'> {{ template.name}} </h1>
<a class="btn btn-primary" style='float:right;' href="{% url 'template-update' template.pk %}"><span class="fa fa-pen"></span></a>
<div class="jumbotron">
{{ template.template |safe  }}
</div>
</div>

{% endblock content %}

doc_gen/templates/template_list.html
{% extends 'base_list.html' %}
{% block table %}
<thead>
<th>Id</th>
<th>Title</th>
<th>Edit</th>
<th>Delete</th>
</thead>
<tbody>
{% for template in object_list %}
<tr>
    <td>{{template.id}}</td>
    <td>
    <a href="{% url 'template-detail' template.pk%}" class="btn btn-success"><span class="fa fa-search">
    {{template.name}}
    </span></a>
    </td>
    <td>{{template.template | safe | truncatewords:20 }}</td>
    <td><a class="btn btn-primary" href="{% url 'template-update' template.pk %}"><span class="fa fa-pen"></span></a></td>
    <td><button class="btn btn-danger" onclick="deleteQuestion('{% url 'template-delete' template.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>

{% endfor %}

</tbody>

<script>
    function deleteQuestion(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Template ?','body':response, 'url': url});
            }
        });
    }
</script>       
{% endblock table %}